# Generated by Django 3.2 on 2023-01-23 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_stripecustomer'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='archive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blog',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
