# Generated by Django 4.1.4 on 2023-01-18 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_plan_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='user',
        ),
    ]
