# Generated by Django 4.1.4 on 2023-01-18 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sub_plan_app', '0003_delete_subscriptionplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('pricing', models.IntegerField()),
                ('validity_days', models.IntegerField()),
                ('highlight', models.BooleanField(default=True)),
            ],
        ),
    ]
