# Generated by Django 4.1.4 on 2023-01-18 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_plan_app', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubPlan',
        ),
    ]
