# Generated by Django 3.2 on 2023-01-20 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_plan_app', '0007_subscription_exp_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='archive',
            field=models.BooleanField(default=False),
        ),
    ]
