# Generated by Django 3.2 on 2023-01-20 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_plan_app', '0009_auto_20230120_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='exp_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='reg_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
